package projectrcr.regioncoderecognizer;

import java.util.HashMap;

/**
 * Created by HICT-HP on 23-11-2015.
 */
public class CountryCodes {
    public HashMap<String, String> hashMapCountryCodes = new HashMap<String, String>();

    {
        hashMapCountryCodes.put("0093", "Afghanistan");
        hashMapCountryCodes.put("00355", "Albania");
        hashMapCountryCodes.put("00213", "Algeria");
        hashMapCountryCodes.put("011684", "American Samoa");
        hashMapCountryCodes.put("00376", "Andorra");
        hashMapCountryCodes.put("00244", "Angola");
        hashMapCountryCodes.put("011264", "Anguilla ");
        hashMapCountryCodes.put("011268", "Antigua and Barbuda");
        hashMapCountryCodes.put("0054", "Argentina");
        hashMapCountryCodes.put("00374", "Armenia");
        hashMapCountryCodes.put("00297", "Aruba");
        hashMapCountryCodes.put("0061", "Australia");
        hashMapCountryCodes.put("0043", "Austria");
        hashMapCountryCodes.put("00994", "Azerbaijan");
        hashMapCountryCodes.put("01124", "Bahamas");
        hashMapCountryCodes.put("00973", "Bahrain");
        hashMapCountryCodes.put("00880", "Bangladesh");
        hashMapCountryCodes.put("011246", "Barbados");
        hashMapCountryCodes.put("00375", "Belarus");
        hashMapCountryCodes.put("0032", "Belgium");
        hashMapCountryCodes.put("00501", "Belize");
        hashMapCountryCodes.put("00229", "Benin");
        hashMapCountryCodes.put("01441", "Bermuda"); //not sure
        hashMapCountryCodes.put("00975", "Bhutan");
        hashMapCountryCodes.put("00591", "'Bolivia, Plurinational State Of'  ");
        hashMapCountryCodes.put("00387", "Bosnia and Herzegovina");
        hashMapCountryCodes.put("00267", "Botswana");
        hashMapCountryCodes.put("0055", "Brazil");
        hashMapCountryCodes.put("00359", "Bulgaria");
        hashMapCountryCodes.put("00226", "Burkina Faso");
        hashMapCountryCodes.put("00257", "Burundi");
        hashMapCountryCodes.put("00855", "Cambodia");
        hashMapCountryCodes.put("001", "Canada");   // not sure
//        hashMapCountryCodes.put("CV", "Cape Verde  ");
//        hashMapCountryCodes.put("KY", "Cayman Islands");
//        hashMapCountryCodes.put("CF", "Central African Republic");
//        hashMapCountryCodes.put("TD", "Chad");
//        hashMapCountryCodes.put("CL", "Chile");
//        hashMapCountryCodes.put("CN", "China");
//        hashMapCountryCodes.put("CX", "Christmas Island");
//        hashMapCountryCodes.put("CC", "Cocos (Keeling) Islands");
//        hashMapCountryCodes.put("CO", "Colombia");
//        hashMapCountryCodes.put("KM", "Comoros");
//        hashMapCountryCodes.put("CG", "Congo");
//        hashMapCountryCodes.put("CD", "'Congo, The Democratic Republic Of The'");
//        hashMapCountryCodes.put("CK", "Cook Islands");
//        hashMapCountryCodes.put("CR", "Costa Rica");
//        hashMapCountryCodes.put("HR", "Croatia");
//        hashMapCountryCodes.put("CU", "Cuba");
//        hashMapCountryCodes.put("CW", "Curaçao");
//        hashMapCountryCodes.put("CY", "Cyprus");
//        hashMapCountryCodes.put("CZ", "Czech Republic");
//        hashMapCountryCodes.put("CI", "Côte D\'Ivoire");
//        hashMapCountryCodes.put("DK", "Denmark");
//        hashMapCountryCodes.put("DJ", "Djibouti");
//        hashMapCountryCodes.put("DM", "Dominica");
//        hashMapCountryCodes.put("DO", "Dominican Republic");
//        hashMapCountryCodes.put("EC", "Ecuador");
//        hashMapCountryCodes.put("EG", "Egypt");
//        hashMapCountryCodes.put("SV", "El Salvador");
//        hashMapCountryCodes.put("GQ", "Equatorial Guinea");
//        hashMapCountryCodes.put("ER", "Eritrea");
//        hashMapCountryCodes.put("EE", "Estonia");
//        hashMapCountryCodes.put("ET", "Ethiopia");
//        hashMapCountryCodes.put("FK", "Falkland Islands  (Malvinas)");
//        hashMapCountryCodes.put("FO", "Faroe Islands");
//        hashMapCountryCodes.put("FJ", "Fiji");
//        hashMapCountryCodes.put("FI", "Finland");
//        hashMapCountryCodes.put("FR", "France");
//        hashMapCountryCodes.put("GF", "French Guiana");
//        hashMapCountryCodes.put("PF", "French Polynesia");
//        hashMapCountryCodes.put("TF", "French Southern Territories");
//        hashMapCountryCodes.put("GA", "Gabon");
//        hashMapCountryCodes.put("GM", "Gambia");
//        hashMapCountryCodes.put("GE", "Georgia");
//        hashMapCountryCodes.put("DE", "Germany");
//        hashMapCountryCodes.put("GH", "Ghana ");
//        hashMapCountryCodes.put("GI", "Gibraltar");
//        hashMapCountryCodes.put("GR", "Greece");
//        hashMapCountryCodes.put("GL", "Greenland");
//        hashMapCountryCodes.put("GD", "Grenada");
//        hashMapCountryCodes.put("GP", "Guadeloupe");
//        hashMapCountryCodes.put("GU", "Guam");
//        hashMapCountryCodes.put("GT", "Guatemala");
//        hashMapCountryCodes.put("GG", "Guernsey");
//        hashMapCountryCodes.put("GN", "Guinea");
//        hashMapCountryCodes.put("GW", "Guinea-Bissau");
//        hashMapCountryCodes.put("GY", "Guyana");
//        hashMapCountryCodes.put("HT", "Haiti");
//        hashMapCountryCodes.put("HM", "Heard and McDonald Islands");
//        hashMapCountryCodes.put("VA", "Holy See (Vatican City State)");
//        hashMapCountryCodes.put("HN", "Honduras");
//        hashMapCountryCodes.put("HK", "Hong Kong");
//        hashMapCountryCodes.put("HU", "Hungary");
//        hashMapCountryCodes.put("IS", "Iceland");
//        hashMapCountryCodes.put("IN", "India");
//        hashMapCountryCodes.put("ID", "Indonesia");
//        hashMapCountryCodes.put("IR", "'Iran, Islamic Republic Of'");
//        hashMapCountryCodes.put("IQ", "Iraq");
//        hashMapCountryCodes.put("IE", "Ireland");
//        hashMapCountryCodes.put("IM", "Isle of Man");
//        hashMapCountryCodes.put("IL", "Israel");
//        hashMapCountryCodes.put("IT", "Italy");
//        hashMapCountryCodes.put("JM", "Jamaica");
//        hashMapCountryCodes.put("JP", "Japan");
//        hashMapCountryCodes.put("JE", "Jersey");
//        hashMapCountryCodes.put("JO", "Jordan");
//        hashMapCountryCodes.put("KZ", "Kazakhstan");
//        hashMapCountryCodes.put("KE", "Kenya");
//        hashMapCountryCodes.put("KI", "Kiribati");
//        hashMapCountryCodes.put("KP", "'Korea, Democratic People\'s Republic Of'");
//        hashMapCountryCodes.put("KR", "'Korea, Republic of'");
//        hashMapCountryCodes.put("KW", "Kuwait");
//        hashMapCountryCodes.put("KG", "Kyrgyzstan");
//        hashMapCountryCodes.put("LA", "Lao People\'s Democratic Republic");
//        hashMapCountryCodes.put("LV", "Latvia");
//        hashMapCountryCodes.put("LB", "Lebanon");
//        hashMapCountryCodes.put("LS", "Lesotho");
//        hashMapCountryCodes.put("LR", "Liberia");
//        hashMapCountryCodes.put("LY", "Libyan Arab Jamahiriya");
//        hashMapCountryCodes.put("LI", "Liechtenstein");
//        hashMapCountryCodes.put("LT", "Lithuania");
//        hashMapCountryCodes.put("LU", "Luxembourg");
//        hashMapCountryCodes.put("MO", "Macao");
//        hashMapCountryCodes.put("MK", "'Macedonia, the Former Yugoslav Republic Of'");
//        hashMapCountryCodes.put("MG", "Madagascar");
//        hashMapCountryCodes.put("MW", "Malawi");
//        hashMapCountryCodes.put("MY", "Malaysia");
//        hashMapCountryCodes.put("MV", "Maldives");
//        hashMapCountryCodes.put("ML", "Mali");
//        hashMapCountryCodes.put("MT", "Malta");
//        hashMapCountryCodes.put("MH", "Marshall Islands");
//        hashMapCountryCodes.put("MQ", "Martinique");
//        hashMapCountryCodes.put("MR", "Mauritania");
//        hashMapCountryCodes.put("MU", "Mauritius");
//        hashMapCountryCodes.put("YT", "Mayotte");
//        hashMapCountryCodes.put("MX", "Mexico");
//        hashMapCountryCodes.put("FM", "'Micronesia, Federated States Of'");
//        hashMapCountryCodes.put("MD", "'Moldova, Republic of'");
//        hashMapCountryCodes.put("MC", "Monaco");
//        hashMapCountryCodes.put("MN", "Mongolia");
//        hashMapCountryCodes.put("ME", "Montenegro");
//        hashMapCountryCodes.put("MS", "Montserrat");
//        hashMapCountryCodes.put("MA", "Morocco");
//        hashMapCountryCodes.put("MZ", "Mozambique");
//        hashMapCountryCodes.put("MM", "Myanmar");
//        hashMapCountryCodes.put("NA", "Namibia");
//        hashMapCountryCodes.put("NR", "Nauru");
//        hashMapCountryCodes.put("NP", "Nepal");
//        hashMapCountryCodes.put("NL", "Netherlands");
//        hashMapCountryCodes.put("AN", "Netherlands Antilles");
//        hashMapCountryCodes.put("NC", "New Caledonia");
//        hashMapCountryCodes.put("NZ", "New Zealand");
//        hashMapCountryCodes.put("NI", "Nicaragua");
//        hashMapCountryCodes.put("NE", "Niger");
//        hashMapCountryCodes.put("NG", "Nigeria");
//        hashMapCountryCodes.put("NU", "Niue");
//        hashMapCountryCodes.put("NF", "Norfolk Island");
//        hashMapCountryCodes.put("MP", "Northern Mariana Islands");
//        hashMapCountryCodes.put("NO", "Norway");
//        hashMapCountryCodes.put("OM", "Oman");
//        hashMapCountryCodes.put("PK", "Pakistan");
//        hashMapCountryCodes.put("PW", "Palau");
//        hashMapCountryCodes.put("PS", "'Palestinian Territory, Occupied'");
//        hashMapCountryCodes.put("PA", "Panama");
//        hashMapCountryCodes.put("PG", "Papua New Guinea");
//        hashMapCountryCodes.put("PY", "Paraguay");
//        hashMapCountryCodes.put("PE", "Peru");
//        hashMapCountryCodes.put("PH", "Philippines");
//        hashMapCountryCodes.put("PN", "Pitcairn");
//        hashMapCountryCodes.put("PL", "Poland");
//        hashMapCountryCodes.put("PT", "Portugal");
//        hashMapCountryCodes.put("PR", "Puerto Rico");
//        hashMapCountryCodes.put("QA", "Qatar");
//        hashMapCountryCodes.put("RO", "Romania");
//        hashMapCountryCodes.put("RU", "Russian Federation");
//        hashMapCountryCodes.put("RW", "Rwanda");
//        hashMapCountryCodes.put("RE", "Réunion");
//        hashMapCountryCodes.put("BL", "Saint Barthélemy");
//        hashMapCountryCodes.put("SH", "'Saint Helena, Ascension and Tristan Da Cunha'");
//        hashMapCountryCodes.put("KN", "Saint Kitts And Nevis");
//        hashMapCountryCodes.put("LC", "Saint Lucia");
//        hashMapCountryCodes.put("MF", "Saint Martin");
//        hashMapCountryCodes.put("PM", "Saint Pierre And Miquelon");
//        hashMapCountryCodes.put("VC", "Saint Vincent And The Grenedines");
//        hashMapCountryCodes.put("WS", "Samoa");
//        hashMapCountryCodes.put("SM", "San Marino");
//        hashMapCountryCodes.put("ST", "Sao Tome and Principe");
//        hashMapCountryCodes.put("SA", "Saudi Arabia");
//        hashMapCountryCodes.put("SN", "Senegal");
//        hashMapCountryCodes.put("RS", "Serbia");
//        hashMapCountryCodes.put("SC", "Seychelles");
//        hashMapCountryCodes.put("SL", "Sierra Leone");
//        hashMapCountryCodes.put("SG", "Singapore");
//        hashMapCountryCodes.put("SX", "Sint Maarten (Dutch part)");
//        hashMapCountryCodes.put("SK", "Slovakia");
//        hashMapCountryCodes.put("SI", "Slovenia");
//        hashMapCountryCodes.put("SB", "Solomon Islands");
//        hashMapCountryCodes.put("SO", "Somalia");
//        hashMapCountryCodes.put("ZA", "South Africa");
//        hashMapCountryCodes.put("GS", "South Georgia and the South Sandwich Islands");
//        hashMapCountryCodes.put("ES", "Spain");
//        hashMapCountryCodes.put("LK", "Sri Lanka");
//        hashMapCountryCodes.put("SD", "Sudan");
//        hashMapCountryCodes.put("SR", "Suriname");
//        hashMapCountryCodes.put("SJ", "Svalbard And Jan Mayen");
//        hashMapCountryCodes.put("SZ", "Swaziland");
//        hashMapCountryCodes.put("SE", "Sweden");
//        hashMapCountryCodes.put("CH", "Switzerland");
//        hashMapCountryCodes.put("SY", "Syrian Arab Republic  ");
//        hashMapCountryCodes.put("TW", "'Taiwan, Province Of China'");
//        hashMapCountryCodes.put("TJ", "Tajikistan");
//        hashMapCountryCodes.put("TZ", "'Tanzania, United Republic of'");
//        hashMapCountryCodes.put("TH", "Thailand");
//        hashMapCountryCodes.put("TL", "Timor-Leste");
//        hashMapCountryCodes.put("TG", "Togo");
//        hashMapCountryCodes.put("TK", "Tokelau");
//        hashMapCountryCodes.put("TO", "Tonga");
//        hashMapCountryCodes.put("TT", "Trinidad and Tobago");
//        hashMapCountryCodes.put("TN", "Tunisia");
//        hashMapCountryCodes.put("TR", "Turkey");
//        hashMapCountryCodes.put("TM", "Turkmenistan");
//        hashMapCountryCodes.put("TC", "Turks and Caicos Islands");
//        hashMapCountryCodes.put("TV", "Tuvalu");
//        hashMapCountryCodes.put("UG", "Uganda");
//        hashMapCountryCodes.put("UA", "Ukraine");
//        hashMapCountryCodes.put("AE", "United Arab Emirates");
//        hashMapCountryCodes.put("GB", "United Kingdom");
//        hashMapCountryCodes.put("US", "United States");
//        hashMapCountryCodes.put("UM", "United States Minor Outlying Islands");
//        hashMapCountryCodes.put("UY", "Uruguay");
//        hashMapCountryCodes.put("UZ", "Uzbekistan");
//        hashMapCountryCodes.put("VU", "Vanuatu");
//        hashMapCountryCodes.put("VE", "'Venezuela, Bolivarian Republic of' ");
//        hashMapCountryCodes.put("VN", "Viet Nam");
//        hashMapCountryCodes.put("VG", "'Virgin Islands, British'");
//        hashMapCountryCodes.put("VI", "'Virgin Islands, U.S.'");
//        hashMapCountryCodes.put("WF", "Wallis and Futuna");
//        hashMapCountryCodes.put("EH", "Western Sahara");
//        hashMapCountryCodes.put("YE", "Yemen");
//        hashMapCountryCodes.put("ZM", "Zambia");
//        hashMapCountryCodes.put("ZW", "Zimbabwe");
//        hashMapCountryCodes.put("AX", "Åland Islands");

    }

    public String checkCountryCode(String paramCountryCode) {
        if (!hashMapCountryCodes.containsKey(paramCountryCode)) {
            return "No Country Code found.";
        }
        return hashMapCountryCodes.get(paramCountryCode);
    }


}


